### ISSUE TITLE
Fix race condition in observability config package

### ISSUE THREAD

**Issue by randalljohnson** [threeport/threeport#271]
In `pkg/config/v0/observability.go` we're experiencing a race condition in which the client attempts to delete the `ObservabilityStackDefinition` and `ObservabilityStackInstance` objects in quick succession. Since the latter requires reconciliation and the client doesn't wait for this to occur, an exception is thrown when the former is attempted. On subsequent attempts to clean up the `ObservabilityStack`, an error is thrown because the `ObservabilityStackInstance` has already been cleaned up, and the `ObservabilityStackDefinition` is not cleaned up.

This can be fixed by a) refactoring this package to use the `util.Operations` abstraction and b) add a wait in the `Delete()` method to ensure that the `ObservabilityStackInstance` is deleted _and_ reconciled before attempting to delete the `ObservabilityStackDefinition`.

**Comment by lander2k2** [comment]
Included in 0.5 release
